// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.API.Data;

#nullable disable

namespace Portfolio.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808073439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.API.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Portfolio.API.Models.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text");

                    b.Property<string>("TelegramUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Assalomu alaykum! Men zamonaviy, tezkor va interaktiv veb-ilovalarni yaratuvchi tajribali .NET va Full-Stack dasturchiman. Orqa fon (Backend) tizimlarida .NET Core hamda ma'lumotlar bazasida PostgreSQL/MSSQL bilan ishlayman. Frontendda esa React va interaktiv 3D grafika (Three.js) yordamida foydalanuvchilarni hayratda qoldiradigan interfeyslarni loyihalashtiraman.",
                            GitHubUrl = "https://github.com",
                            LinkedInUrl = "https://linkedin.com",
                            Name = "Ikromov",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&q=80",
                            ResumeUrl = "#",
                            TelegramUrl = "https://t.me",
                            Title = ".NET & Full-Stack Developer"
                        });
                });

            modelBuilder.Entity("Portfolio.API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("TechStack")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "O'quvchilar bilimini baholash va testlarni onlayn topshirish uchun yaratilgan mukammal tizim. .NET Core Web API, PostgreSQL va React texnologiyalari orqali ishlab chiqilgan.",
                            GithubUrl = "https://github.com",
                            ImageUrl = "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80",
                            LiveUrl = "https://example.com",
                            Order = 1,
                            TechStack = new List<string> { ".NET Core 10", "React", "PostgreSQL", "Entity Framework" },
                            Title = "Test Platform & LMS"
                        },
                        new
                        {
                            Id = 2,
                            Description = "RabbitMQ yordamida navbatlar boshqaruvi va Redis kesh tizimiga asoslangan, yuqori yuklamalarga chidamli elektron do'kon orqa fon (backend) tizimi.",
                            GithubUrl = "https://github.com",
                            ImageUrl = "https://images.unsplash.com/photo-1557821552-17105176677c?w=600&q=80",
                            LiveUrl = "https://example.com",
                            Order = 2,
                            TechStack = new List<string> { ".NET Microservices", "RabbitMQ", "Redis", "PostgreSQL" },
                            Title = "E-Commerce Microservices"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Three.js va React Three Fiber asosida mahsulotlarni 3D model shaklida ko'rish va ularning rang hamda dizaynini real vaqtda o'zgartirish imkonini beruvchi ilova.",
                            GithubUrl = "https://github.com",
                            ImageUrl = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80",
                            LiveUrl = "https://example.com",
                            Order = 3,
                            TechStack = new List<string> { "React", "Three.js", "Vite", "Vanilla CSS" },
                            Title = "3D Interactive Showroom"
                        });
                });

            modelBuilder.Entity("Portfolio.API.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            IconName = "Terminal",
                            Name = "C# / .NET 10",
                            Percentage = 95
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            IconName = "Cpu",
                            Name = "ASP.NET Core / EF Core",
                            Percentage = 92
                        },
                        new
                        {
                            Id = 3,
                            Category = "Database",
                            IconName = "Database",
                            Name = "PostgreSQL / MSSQL",
                            Percentage = 88
                        },
                        new
                        {
                            Id = 4,
                            Category = "Frontend",
                            IconName = "Globe",
                            Name = "React.js / Vite",
                            Percentage = 82
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frontend",
                            IconName = "Sparkles",
                            Name = "Three.js / WebGL",
                            Percentage = 75
                        },
                        new
                        {
                            Id = 6,
                            Category = "DevOps",
                            IconName = "Settings",
                            Name = "Docker / CI-CD",
                            Percentage = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
